name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for required files
        run: |
          for file in index.html README.md _sidebar.md about.md conferences.md resources.md; do
            if [ ! -f "$file" ]; then
              echo "Error: $file is missing"
              exit 1
            fi
          done
          echo "All required files are present"
