# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Docsify CLI
        run: npm install -g docsify-cli

      - name: Build Docsify site
        run: docsify init ./docs

      - name: Copy files to docs
        run: |
          cp index.html ./docs/
          cp README.md ./docs/
          cp _sidebar.md ./docs/
          cp about.md ./docs/
          cp conferences.md ./docs/
          cp resources.md ./docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
